SELECT s.NOM_SETOR, AVG(i.VLR_VENDA - i.VLR_CUSTO) AS lucro_medio
FROM ITEM_NOTA i
JOIN PRODUTO p ON p.COD_PRODUTO = i.COD_PRODUTO
JOIN SETOR s ON s.COD_SETOR = p.COD_SETOR
GROUP BY s.NOM_SETOR;
-- Lucro médio por setor